name: CI/CD 

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/faridimamns/tyoris:latest .
          docker push ghcr.io/faridimamns/tyoris:latest

  deploy-development:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: SSH to Development Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.MY_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/Faridimamns/tyoris:latest
            docker run -d --name tyoris-dev -p 8080:80 ghcr.io/Faridimamns/tyoris:latest

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: SSH to Production Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.MY_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/Faridimamns/tyoris:latest
            docker run -d --name tyoris-prod -p 8081:80 ghcr.io/Faridimamns/tyoris:latest
