name: Deploy on Development Push

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tyoris:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /root/proyek

            # Pull the latest changes from the development branch
            git pull origin development
            
            # Build the Docker image with the latest code
            docker build -t tyoris .

            # Stop and remove old application container if it exists
            docker stop tyoris || true
            docker rm tyoris || true

            # Run the new application container
            docker run -d --name tyoris -p 80:80 tyoris

            # Install to /var/www/html (example path)
            mkdir -p /var/www/html
            cp -r . /var/www/html
